#配置端口号
server:
  port: 8081

#配置数据库
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/data?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: maoyan123


#数据库字段的下划线转驼峰,比如数据库字段cron_id，实体类就是cronId
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true